// Theme configurations for the Sweet Shop
export const THEMES = {
  default: {
    name: 'Default',
    gradient: 'from-blue-50 via-indigo-50 to-purple-50',
    cardGradient: 'from-purple-100 to-pink-100',
    accent: 'bg-purple-600',
    accentHover: 'hover:bg-purple-700',
    text: 'text-purple-600',
    border: 'border-purple-200',
    pill: 'bg-purple-100 text-purple-700',
    pillActive: 'bg-purple-600 text-white',
  },
  strawberry: {
    name: 'Strawberry',
    gradient: 'from-red-50 via-pink-50 to-rose-50',
    cardGradient: 'from-pink-200 to-rose-300',
    accent: 'bg-red-500',
    accentHover: 'hover:bg-red-600',
    text: 'text-red-500',
    border: 'border-red-200',
    pill: 'bg-red-100 text-red-700',
    pillActive: 'bg-red-500 text-white',
  },
  orange: {
    name: 'Orange',
    gradient: 'from-orange-50 via-amber-50 to-yellow-50',
    cardGradient: 'from-orange-200 to-amber-300',
    accent: 'bg-orange-500',
    accentHover: 'hover:bg-orange-600',
    text: 'text-orange-500',
    border: 'border-orange-200',
    pill: 'bg-orange-100 text-orange-700',
    pillActive: 'bg-orange-500 text-white',
  },
  chocolate: {
    name: 'Chocolate',
    gradient: 'from-amber-50 via-orange-50 to-yellow-50',
    cardGradient: 'from-amber-200 to-orange-300',
    accent: 'bg-amber-700',
    accentHover: 'hover:bg-amber-800',
    text: 'text-amber-700',
    border: 'border-amber-200',
    pill: 'bg-amber-100 text-amber-700',
    pillActive: 'bg-amber-700 text-white',
  },
  mint: {
    name: 'Mint',
    gradient: 'from-emerald-50 via-teal-50 to-cyan-50',
    cardGradient: 'from-emerald-200 to-teal-300',
    accent: 'bg-emerald-500',
    accentHover: 'hover:bg-emerald-600',
    text: 'text-emerald-500',
    border: 'border-emerald-200',
    pill: 'bg-emerald-100 text-emerald-700',
    pillActive: 'bg-emerald-500 text-white',
  },
  blueberry: {
    name: 'Blueberry',
    gradient: 'from-blue-50 via-indigo-50 to-violet-50',
    cardGradient: 'from-blue-200 to-indigo-300',
    accent: 'bg-blue-500',
    accentHover: 'hover:bg-blue-600',
    text: 'text-blue-500',
    border: 'border-blue-200',
    pill: 'bg-blue-100 text-blue-700',
    pillActive: 'bg-blue-500 text-white',
  },
};

export default THEMES;
